### ISSUE TITLE
Support for Kotlin's also idiom

### ISSUE THREAD

**Issue by eriklagerholm** [danneu/kotlin-result#3]
Loving this implementation, so nice and simple yet flexible!

Would you consider adding something like this:

```Kotlin
fun <V, E> Result<V, E>.also(block: () -> Unit): Result<V, E> = when (this) {
    is Result.Ok<V> -> {
        block()
        this
    }
    is Result.Err<E> -> this
}

fun <V, E> Result<V, E>.onErrorAlso(block: () -> Unit): Result<V, E> = when (this) {
    is Result.Ok<V> -> this
    is Result.Err<E> -> {
        block()
        this
    }
}
```

Or is there a way to do this already? Just to execute an arbitrary block of code based on the results. It would enable extensions such as:

```Kotlin
fun <V, E> Result.Companion.inTransaction(transactionManager: PlatformTransactionManager, block: () -> Result<V, E>): Result<V, E> {
    val transaction = transactionManager.getTransaction(TransactionDefinition.withDefaults())
    return block().also {
        transactionManager.commit(transaction)
    }.onErrorAlso {
        transactionManager.rollback(transaction)
    }
}
```

All the best

**Comment by danneu** [comment]
Thanks @eriklagerholm!

I don't think I've used Kotlin since the year I published this library so I don't have any strong opinions here nor am I in much of a place to help.

You are probably the only person using this library, so be sure to just copy it into your project if you're using it and then feel free to let me know about any helpful changes you've made to it. Adding Kotlin's scoping functions seems like a good idea.

----

Btw, just out of curiosity and at risk of over-examining your demo code, I think you'd wanna pass `transaction` into the block:

```kotlin
inTransaction { tx -> 
    tx.execute("insert 1 into foo;")
    tx.execute("insert 2 into foo;")
}
```

I think you'd also have to wrap the block in a try/catch so that you're lifting exceptions into `Result.Err`.

I've written that sort of transaction code a lot of times, so just remember that `BEGIN` can fail, `COMMIT` can fail, and even `ROLLBACK` can fail. Here's how I've done that in a small Javascript library: https://github.com/danneu/pg-extra/blob/be0e1a9fd513296e9bedcf8e98c8e515f8c0e5db/src/lib/Methods.js#L69-L116

**Comment by eriklagerholm** [comment]
Oh I see! I guess people have gone for the more verbose https://github.com/michaelbull/kotlin-result. But for me yours is just perfectly scoped.

Thank you, those are very helpful considerations! I guess my current implementation is a bit naive :)
